"""Wire schemas for the /agents endpoints."""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field, field_validator


_SUPPORTED_ANALYSTS = {"market", "social", "news", "fundamentals"}
_SUPPORTED_LANGUAGES = {"en-US", "zh-TW", "zh-CN", "ja-JP", "ko-KR", "de-DE"}


class RunRequest(BaseModel):
    """POST /agents/run request body.

    Mirrors TradingAgents' ``TradingAgentsConfig`` knobs — ``max_debate_rounds``,
    ``max_risk_discuss_rounds``, ``reasoning_effort``, ``response_language`` —
    plus our wire fields (``run_id``, ``deep_thinking``).

    Defaults are conservative: shortest debate (1 round each), medium reasoning,
    English. Callers tune up per-run via the Run-cost-estimate UI.

    ``run_id`` is generated by the Nuxt proxy when it INSERTs the
    ``agent_runs`` row and forwarded here so both layers share one canonical id
    — without it the api would mint its own uuid, the run-start event would
    emit that fresh id, and the URL the client persists wouldn't match the row
    in agent_runs (refresh = 404).
    """

    symbol: str = Field(..., min_length=1, max_length=20)
    trade_date: date | None = None
    max_debate_rounds: int = Field(1, ge=1, le=3)
    max_risk_discuss_rounds: int = Field(1, ge=1, le=3)
    deep_thinking: bool = True
    reasoning_effort: Literal["low", "medium", "high", "xhigh", "max"] = "medium"
    response_language: Literal[
        "en-US", "zh-TW", "zh-CN", "ja-JP", "ko-KR", "de-DE"
    ] = "en-US"
    selected_analysts: list[str] = Field(
        default_factory=lambda: ["market", "social", "news", "fundamentals"]
    )
    run_id: str | None = Field(default=None, min_length=1, max_length=64)

    @field_validator("selected_analysts")
    @classmethod
    def _normalize_analysts(cls, v: list[str]) -> list[str]:
        # Accept any case, dedupe in input order, reject unknowns. Empty list
        # means "use the full default" — the agents pipeline must run at
        # least one analyst.
        seen: set[str] = set()
        out: list[str] = []
        for raw in v:
            name = raw.strip().lower()
            if name not in _SUPPORTED_ANALYSTS:
                raise ValueError(
                    f"unknown analyst {raw!r}; supported: {sorted(_SUPPORTED_ANALYSTS)}"
                )
            if name not in seen:
                seen.add(name)
                out.append(name)
        if not out:
            raise ValueError("selected_analysts must contain at least one analyst")
        return out
