"""Wire schemas for the /agents endpoints."""

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, Field


class RunRequest(BaseModel):
    """POST /agents/run request body.

    `trade_date` defaults to today (UTC) when omitted, set in the router.
    `max_debate_rounds` is bounded to keep paid LLM costs predictable.
    `run_id` is generated by the Nuxt proxy when it INSERTs the
    ``agent_runs`` row and forwarded here so both layers share one
    canonical id — without it, the api would mint its own uuid, the
    run-start event would emit that fresh id, and the URL the client
    persists wouldn't match the row in agent_runs (refresh = 404).
    """

    symbol: str = Field(..., min_length=1, max_length=20)
    trade_date: date | None = None
    max_debate_rounds: int = Field(1, ge=1, le=3)
    deep_thinking: bool = True
    run_id: str | None = Field(default=None, min_length=1, max_length=64)
